### ✅ Registro de usuario
POST http://localhost:3000/api/auth/registro
Content-Type: application/json

{
  "nombre": "Andrea Torres",
  "correo": "andrea@example.com",
  "contraseña": "segura123",
  "rol": "usuario",
  "puede_crear_usuarios": false,
  "activo": true,
  "foto_url": "https://i.pravatar.cc/150?img=5"
}

### ✅ Login de usuario
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "correo": "andrea@example.com",
  "contraseña": "segura123"
}

### ✅ Login de usuario con rol de administrador
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "correo": "admin@example.com",
  "contraseña": "segura123"
}

### ✅ Crear incidencia (requiere TOKEN)
# 🔁 Reemplaza el token con el JWT obtenido en el login
POST http://localhost:3000/api/incidentes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjYyYjlkLWRiYmQtNGQ5YS1iYmM3LTI2YTE4ODIwMDNlOCIsImNvcnJlbyI6ImFuZHJlYUBleGFtcGxlLmNvbSIsInJvbCI6InVzdWFyaW8iLCJpYXQiOjE3NTU4NTIzNjksImV4cCI6MTc1NTg1NTk2OX0.9FjkzsCMSQ-N4snTD4GAyA3lmeoRZF9VVIKgdEzTY6Y
Content-Length: 0

{
  "titulo": "Extintor vencido en bodega",
  "descripcion": "El extintor ubicado en la bodega tiene fecha de vencimiento pasada.",
  "urgencia": "alto"
}


### admin login
POST http://localhost:3000/admin/login
Content-Type: application/json

{
  "correo": "sofia@aurontek.com",
  "contraseña": "secreta123"
}

### Registrar nueva empresa con contratante y licencia
POST http://localhost:3000/admin/empresas/crear
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEzMTViMjYwLWZmYjktNDYxNy05YjFjLWExOTA4NWUxZmNiYSIsImNvcnJlbyI6InNvZmlhQGF1cm9udGVrLmNvbSIsIm5vbWJyZSI6IlNvZsOtYSBSZXllcyIsImFkbWluIjp0cnVlLCJpYXQiOjE3NTU4NTA5MTAsImV4cCI6MTc1NTg1NDUxMH0.tLDFLEgH0q-VYl622lSrWMO5li5rhAmbHQ35XdzzE4Y

{
  "nombre_empresa": "Grupo Omega",
  "rfc": "OME800123ABC",
  "telefono": "5551234567",
  "direccion": "Av. Central 123",
  "correo_contacto": "contacto@omega.com",

  "contratante": {
    "nombre": "Laura Pérez",
    "correo": "laura@omega.com",
    "telefono": "5559876543",
    "puesto": "Gerente TI"
    
  },

  "licencia": {
    "fecha_inicio": "2025-08-01",
    "fecha_fin": "2026-08-01",
    "plan": "Pro"
  }
}



