### ✅ Registro de usuario
POST http://localhost:3000/api/auth/registro
Content-Type: application/json

{
  "nombre": "Andrea Torres",
  "correo": "andrea@example.com",
  "contraseña": "segura123",
  "rol": "usuario",
  "puede_crear_usuarios": false,
  "activo": true,
  "foto_url": "https://i.pravatar.cc/150?img=5"
}

### ✅ Login de usuario
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "correo": "laura@omega.com",
  "contraseña": "3ty7q!U!pX"
}

### ✅ Login admin sistema
POST http://localhost:3000/api/admin-sistema/login
Content-Type: application/json

{
  "correo": "sofia@aurontek.com",
  "contraseña": "admin123"
}

### ✅ Crear incidencia (requiere TOKEN)
# 🔁 Reemplaza el token con el JWT obtenido en el login
POST http://localhost:3000/api/incidentes
Content-Type: application/json
Authorization: Bearer 
Content-Length: 0

{
  "titulo": "Extintor vencido en bodega",
  "descripcion": "El extintor ubicado en la bodega tiene fecha de vencimiento pasada.",
  "urgencia": "alto"
}




### Registrar nueva empresa con contratante y licencia
POST http://localhost:3000/admin/empresas/crear
Content-Type: application/json
Authorization: Bearer 

{
  "nombre_empresa": "Grupo Omega",
  "rfc": "OME800123ABC",
  "telefono": "5551234567",
  "direccion": "Av. Central 123",
  "correo_contacto": "contacto@omega.com",

  "contratante": {
    "nombre": "Laura Pérez",
    "correo": "laura@omega.com",
    "telefono": "5559876543",
    "puesto": "Gerente TI"
    
  },

  "licencia": {
    "fecha_inicio": "2025-08-01",
    "fecha_fin": "2026-08-01",
    "plan": "Pro"
  }
}




